SELECT OWNER,
       SEGMENT_NAME,
       SEGMENT_TYPE,
       BYTES / 1024 / 1024 AS USE_MB,
       TABLESPACE_NAME
  FROM DBA_SEGMENTS
 WHERE OWNER NOT IN ('ANONYMOUS',
                     'CTXSYS',
                     'DBSNMP',
                     'DIP',
                     'DMSYS',
                     'EXFSYS',
                     'MDDATA',
                     'MDSYS',
                     'MGMT_VIEW',
                     'OLAPSYS',
                     'ORACLE_OCM',
                     'ORDPLUGINS',
                     'ORDSYS',
                     'OUTLN',
                     'SCOTT',
                     'SI_INFORMTN_SCHEMA',
                     'SYS',
                     'SYSMAN',
                     'SYSTEM',
                     'TSMSYS',
                     'WMSYS',
                     'XDB')